os:
  - linux
    dist: xenial
  - osx
language: c
compiler: gcc
script: make
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libpq-dev libmysqlclient-dev libmariadbclient-dev unixodbc-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
addons:
  apt:
    update: true