language: c
os:
  - linux
    dist: bionic
compiler: gcc
script: make
before_install:
  - sudo apt-get -y install libpq-dev libmysqlclient-dev libmariadbclient-dev unixodbc-dev
addons:
  apt:
    update: true